name: Build
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        required: true
        description: Deploy service

env:
  INITIAL_VERSION: 3.0.0
  DEFAULT_BUMP: patch
  TRUNCATE_PRERELEASE: false

  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    outputs:
      version: ${{ steps.npm.outputs.version }}
      prerelease: ${{ steps.npm.outputs.prerelease }}
      deploy: ${{ steps.npm.outputs.deploy }}

    steps:
      - name: Build npm package
        uses: tfso/gh-action-helpers/npm-build@v1.8.0
        id: npm
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_GLOBAL_TOKEN: ${{ secrets.TFSO_REPO_READ }}
          NPM_TOKEN: ${{ secrets.NPM_TFSO_TOKEN }}
          INITIAL_VERSION: ${{ env.INITIAL_VERSION }}
          TRUNCATE_PRERELEASE: ${{ env.TRUNCATE_PRERELEASE }}
          NODE_VERSION: ${{ env.NODE_VERSION }}

      - name: Build and push Docker image
        uses: tfso/gh-action-helpers/build-and-push@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ format('tfso/{0}', github.event.repository.name) }}:${{ steps.npm.outputs.version }}
          push: ${{ steps.npm.outputs.deploy == 'true' || github.event.inputs.deploy == 'true' }}

  tag:
    if: needs.build.outputs.deploy == 'true' || github.event.inputs.deploy == 'true'
    needs: build
    runs-on: ubuntu-latest
    name: Push tag
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TFSO_REPO_TAG }}
          CUSTOM_TAG: ${{ needs.build.outputs.version }}