name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        required: true
        description: Deploy package

env:
  INITIAL_VERSION: 3.0.0
  DEFAULT_BUMP: patch

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    outputs:
      version: ${{ steps.npm.outputs.version }}
      prerelease: ${{ steps.npm.outputs.prerelease }}
      deploy: ${{ steps.npm.outputs.deploy }}

    steps:
      - name: build npm package
        uses: tfso/action-helpers/npm-build@v1
        id: npm
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TFSO_TOKEN }}
          FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
          INITIAL_VERSION: ${{ env.INITIAL_VERSION }}
          TRUNCATE_PRERELEASE: true

  tag:
    if: needs.build.outputs.deploy == 'true' || github.event.inputs.deploy == 'true'
    needs: build
    runs-on: ubuntu-latest
    name: push tag
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: push tag
        uses: tfso/action-helpers/tag@v1
        with:
          GITHUB_TOKEN: ${{ secrets.TFSO_REPO_TAG }}
          tag: ${{ needs.build.outputs.version }}
