name: (Prerelease) Package

on:
    push:
        tags:
            - 'v[0-9]+\.[0-9]+\.[0-9]+-*' # only preleases, eg v1.0.1-beta.1

env:
  NODE_VERSION: 20
  FILES: |
    dist/
    src/
    package.json
    package-lock.json
    README.md

jobs:
  setup:
    runs-on: ubuntu-latest
    name: find version
    outputs:
      version: v${{ steps.semver.outputs.fullversion }}
      prerelease: ${{ steps.semver.outputs.prerelease }}
    steps:
      - name: extract tag version
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: 'refs\/tags\/v(.*)$'

  build:
    if: needs.setup.outputs.prerelease
    runs-on: ubuntu-latest
    name: download package
    needs: setup
    steps:
      - name: build npm package
        uses: tfso/action-helpers/npm-build@v1
        id: npm
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TFSO_TOKEN }}
          FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
          CUSTOM_TAG: ${{ needs.setup.outputs.version }}

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ env.FILES }}
          retention-days: 7

  publish-npm:
    runs-on: ubuntu-latest
    name: publish to npm
    needs: [setup, build]
    steps:
      - name: download package
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
          scope: '@tfso'

      - name: extract package version
        id: semver_package
        uses: Saionaro/extract-package-version@v1.0.6

      - name: compare package version with tag version
        if: format('v{0}', steps.semver_package.outputs.version) != needs.setup.outputs.version
        run: |
          echo "version from package v${{ steps.semver_package.outputs.version }} is not matching tag version ${{ needs.setup.outputs.version }}"
          exit 1

      - name: extract npm tag
        id: npmpublish
        run: |
          echo "tag=$(echo "${PRERELEASE}" | sed 's/v\?[0-9]*\.[0-9]*\.[0-9]*\-\([^.+]*\).*/\1/')" >> $GITHUB_OUTPUT
        env:
          PRERELEASE: ${{ steps.semver_package.outputs.version }}          

      - name: publish prerelease version
        run: |
          npm publish --access public --tag ${{ steps.npmpublish.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    name: publish
    needs: [setup, build]
    steps:
      - name: download package
        uses: actions/download-artifact@v4
        with:
          name: package

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tfso'

      - name: extract package version
        id: semver_package
        uses: Saionaro/extract-package-version@v1.0.6

      - name: compare package version with tag version
        if: format('v{0}', steps.semver_package.outputs.version) != needs.setup.outputs.version
        run: |
          echo "version from package v${{ steps.semver_package.outputs.version }} is not matching tag version ${{ needs.setup.outputs.version }}"
          exit 1

      - name: extract npm tag
        id: npmpublish
        run: |
          echo "tag=$(echo "${PRERELEASE}" | sed 's/v\?[0-9]*\.[0-9]*\.[0-9]*\-\([^.+]*\).*/\1/')" >> $GITHUB_OUTPUT
        env:
          PRERELEASE: ${{ steps.semver_package.outputs.version }}

      - name: publish prerelease version
        run: |
          npm publish  --access public --tag ${{ steps.npmpublish.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
